name: Sync Docker Images

on: 
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Login to Alibaba Cloud Registry
        env:
          ALIBABA_CLOUD_REGISTRY: registry.cn-beijing.aliyuncs.com
          USERNAME: pengnz
          PASSWORD: 160014nuo
        run: |
          echo $PASSWORD | docker login $ALIBABA_CLOUD_REGISTRY -u $USERNAME --password-stdin

      - name: Use Skopeo Tools to Sync Images to Alibaba Cloud
        run: |
          skopeo copy docker://docker.io/library/elasticsearch:7.12.1 docker://registry.cn-beijing.aliyuncs.com/wulan/elasticsearch:7.12.1
          skopeo copy docker://docker.io/library/kibana:7.12.1 docker://registry.cn-beijing.aliyuncs.com/wulan/kibana:7.12.1
          skopeo copy docker://docker.io/library/elasticsearch:7.12.1 docker://registry.cn-beijing.aliyuncs.com/wulan/elasticsearch:8.10.2
          skopeo copy docker://docker.io/library/kibana:7.12.1 docker://registry.cn-beijing.aliyuncs.com/wulan/kibana:8.10.2
          skopeo copy docker://docker.io/xuxueli/xxl-job-admin:2.3.1 docker://registry.cn-beijing.aliyuncs.com/wulan/xxl-job-admin:2.3.1
          skopeo copy docker://docker.io/library/nginx:1.24.0 docker://registry.cn-beijing.aliyuncs.com/wulan/nginx:1.24.0
          skopeo copy docker://docker.io/canal/canal-server:v1.1.1 docker://registry.cn-beijing.aliyuncs.com/wulan/canal-server:v1.1.1
