name: Sync Docker Images

on: 
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Login to Alibaba Cloud Registry
        env:
          ALIBABA_CLOUD_REGISTRY: registry.cn-beijing.aliyuncs.com
          USERNAME: pengnz
          PASSWORD: 160014nuo
        run: |
          echo $PASSWORD | docker login $ALIBABA_CLOUD_REGISTRY -u $USERNAME --password-stdin

      - name: Use Skopeo Tools to Sync Images to Alibaba Cloud
        run: |
          skopeo copy docker://docker.io/library/rabbitmq:3.8.34 docker://registry.cn-beijing.aliyuncs.com/wulan/rabbitmq:3.8.34
          skopeo copy docker://docker.io/library/redis:6.2.14 docker://registry.cn-beijing.aliyuncs.com/wulan/redis:6.2.14
          skopeo copy docker://docker.io/nacos/nacos-server:1.4.1 docker://registry.cn-beijing.aliyuncs.com/wulan/nacos-server:1.4.1
          skopeo copy docker://docker.io/minio/minio:RELEASE.2022-09-07T22-25-02Z docker://registry.cn-beijing.aliyuncs.com/wulan/minio:RELEASE.2022-09-07T22-25-02Z
